swagger:
  ui:
    enable: true

helloworld:
  message: fuck-62-u

server:
  port: 9999

spring:
  thymeleaf:
    cache: true

management:
  security:
    enabled: false

#spring:
#  rabbitmq:
#    username: root
#    password: root
#    virtual-host: /order_eventstream
#    host: 10.0.40.151
#    port: 5672